### ISSUE TITLE
predicting VL molecules

### ISSUE THREAD

**Issue by avilella** [dina-lab3D/NanoNet#2]
Hi,

Is it possible to predict the 3D structure of a light chain VJ leaderless sequence? I tried with one, and although it produces an output, the structure is very different from any other method I tried. The VH of the antibody, predicted by NanoNet, is much closer to the prediction of other methods.

**Comment by tomerco4** [comment]
Hi,
NanoNet currently does not support modeling of light chains. It was trained only on heavy chains (heavy chains of mAb and nanobodies), so while you can give it a light chain sequence the structure will not be useful...

We are currently working on extending NanoNet to support light chains as well, hopefully it will be ready soon. 
Happy to answer any more questions.

Tomer.
