### ISSUE TITLE
Can not work when >100 sequences inputed

### ISSUE THREAD

**Issue by youngh81** [dina-lab3D/NanoNet#4]
Hi,
I am trying to build structures for a large number of nb sequence, however I found it did not work when the sequences is more than 100. The error information is: 

 Traceback (most recent call last):
  File "/home/dell/NanoNet/NanoNet.py", line 245, in <module>
    run_nanonet(args.fasta, nanonet_model, args.single_file, output_directory, args.modeller, scwrl_path)
  File "/home/dell/NanoNet/NanoNet.py", line 174, in run_nanonet
    input_matrix[i] = generate_input(sequences[i])
  File "/home/dell/NanoNet/NanoNet.py", line 71, in generate_input
    seq_matrix[i][AA_DICT[seq[i]]] = 1
KeyError: 'y'

I used modeller for side chain building, how can I fixed this issue?
Thanks.

**Comment by tomerco4** [comment]
Hi sorry for the late replay.
The error is not because of the number of sequences but because one of your sequences has a lower case 'y' in it. Making sure all of your sequences are upper case only will solve this issue.

We will definitely add this check in future releases.

Thanks.
